# Site
title: Segfault
author: alxbl
description: Debugging, Reverse Engineering, Security and Low-level tinkering. I also sometimes blog about non-software related things.
language: en
timezone: America/Montreal

# URL
url: https://segfault.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

# Syntax Highlighting
highlight:
  enable: true
  hljs: true
  line_number: true
  auto_detect: false
  gutter: true
  wrap: false

marked:
    breaks: false

# Beautify
beautify:
  types:
    - html
    - css
    - js
  exclude:
    - '*.min.css'
    - '*.min.js'
  html:
    'indent_inner_html': false
    'indent_size': 2
    'indent_with_tabs': false
    'preserve_newlines': false
  css:
    'indent_size': 2
    'newline_between_rules': true
    'indent_with_tabs': false
  js:
    'indent_size': 2
    'indent_with_tabs': false

# Home page setting
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# RSS
feed:
    type: atom
    path: /atom.xml
    limit: 20
    hub:
    content: false
    content_limit: 140
    content_limit_delim: ' '

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
theme: segfault

# Deployment
deploy:
  type:
